title:             하백의신부의 코딩 개발일지
email:             your-email@example.com
description:       끄적끄적 적는 블로그
author:            Start Bootstrap
baseurl:           
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
